-- ============================================================
-- Élégance — Supabase schema (tables, security, order logic)
-- Paste this whole file into: Supabase Dashboard > SQL Editor > New query > Run
--
-- Safe to run again later: policies and functions are dropped and recreated.
--
-- IMPORTANT — this file is the real security of the site.
-- The website is static, so the browser talks to Postgres directly and anyone
-- can call the API without loading your pages. Nothing in js/ protects data;
-- the rules below do.
-- ============================================================

-- ---------- CATEGORIES ----------
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name_fr text not null,
  name_ar text not null,
  name_en text not null,
  sort int not null default 0,
  created_at timestamptz not null default now()
);

-- ---------- PRODUCTS ----------
create table if not exists products (
  id bigint generated by default as identity primary key,
  name_fr text not null,
  name_ar text not null,
  name_en text not null,
  description_fr text default '',
  description_ar text default '',
  description_en text default '',
  price numeric not null check (price >= 0),
  compare_at_price numeric check (compare_at_price >= 0),
  photos text[] not null default '{}',
  sizes text[] not null default '{"S","M","L","XL","XXL"}',
  category_id bigint references categories(id) on delete set null,
  stock int not null default 0 check (stock >= 0),
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------- ORDERS (cash on delivery only) ----------
create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null,
  zone text not null,                -- delivery zone (wilaya / area)
  delivery_fee numeric not null default 0,
  items jsonb not null,              -- [{product_id, name_*, size, price, qty, photo}]
  subtotal numeric not null,
  total numeric not null,
  status text not null default 'new' -- new | confirmed | shipped | delivered | cancelled
        check (status in ('new','confirmed','shipped','delivered','cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on orders (created_at desc);
create index if not exists orders_phone_idx on orders (phone, created_at desc);

-- ---------- SETTINGS (store name, phone, delivery zones) ----------
create table if not exists settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into settings (key, value) values
  ('store', '{"name":"Élégance","phone":"","email":""}'),
  ('zones', '[{"name":"Alger","fee":600},{"name":"Oran","fee":800},{"name":"Constantine","fee":800},{"name":"Blida","fee":600},{"name":"Sétif","fee":800},{"name":"Annaba","fee":800},{"name":"Tizi Ouzou","fee":700},{"name":"Autre wilaya","fee":1000}]')
on conflict (key) do nothing;

-- Upgrade older installs: identity columns must accept an explicit id so that
-- the admin panel's "save" (an upsert, which sends the id) can update a row.
alter table categories alter column id set generated by default;
alter table products   alter column id set generated by default;
alter table orders     alter column id set generated by default;


-- ============================================================
-- WHO IS THE OWNER
--
-- "logged in" is not the same as "the owner": anyone can sign up with the
-- public anon key. Ownership is an explicit list of one.
-- ============================================================
create table if not exists owners (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table owners enable row level security;
-- deliberately no policies: this table is unreachable through the public API

create or replace function public.is_owner()
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$ select exists (select 1 from owners where user_id = auth.uid()) $$;

-- The FIRST account created becomes the owner. Every later signup gets nothing.
create or replace function public.claim_ownership()
returns trigger
language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  insert into owners (user_id)
  select new.id where not exists (select 1 from owners);
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.claim_ownership();


-- ============================================================
-- PLACING AN ORDER
--
-- Visitors cannot insert into `orders` directly — if they could, they would
-- also choose the prices. They call this function instead, which rebuilds the
-- basket from the real products table and ignores every number the browser
-- sent. Stock is reserved in the same transaction.
-- ============================================================
create or replace function public.place_order(
  p_name    text,
  p_phone   text,
  p_address text,
  p_zone    text,
  p_items   jsonb
)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  line  jsonb;
  prod  products%rowtype;
  v_pid bigint;
  v_qty int;
  v_size text;
  clean jsonb := '[]'::jsonb;
  v_sub numeric := 0;
  v_fee numeric;
  v_id  bigint;
begin
  p_name    := left(btrim(coalesce(p_name,    '')), 120);
  p_phone   := left(btrim(coalesce(p_phone,   '')), 30);
  p_address := left(btrim(coalesce(p_address, '')), 400);
  p_zone    := left(btrim(coalesce(p_zone,    '')), 80);

  if p_name = '' or p_phone = '' or p_address = '' then
    raise exception 'MISSING_FIELDS';
  end if;
  if p_phone !~ '^[0-9+][0-9+ -]{7,}$' then
    raise exception 'INVALID_PHONE';
  end if;

  -- light anti-spam: the form is open to the whole internet
  if (select count(*) from orders
      where phone = p_phone and created_at > now() - interval '1 hour') >= 5 then
    raise exception 'TOO_MANY_ORDERS';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'INVALID_CART';
  end if;

  -- the delivery fee comes from settings, never from the browser
  select (z->>'fee')::numeric into v_fee
  from settings s, jsonb_array_elements(s.value) z
  where s.key = 'zones' and z->>'name' = p_zone
  limit 1;
  if v_fee is null then
    raise exception 'UNKNOWN_ZONE';
  end if;

  for line in select * from jsonb_array_elements(p_items) loop
    -- the browser may send anything at all here, including text where a
    -- number belongs, so a failed cast is just a rejected order
    begin
      v_pid := (line->>'product_id')::bigint;
      v_qty := floor((line->>'qty')::numeric)::int;
    exception when others then
      raise exception 'INVALID_CART';
    end;

    if v_qty is null or v_qty < 1 or v_qty > 20 then
      raise exception 'INVALID_CART';
    end if;

    select * into prod from products
    where id = v_pid and active = true
    for update;
    if not found then
      raise exception 'PRODUCT_UNAVAILABLE';
    end if;
    if prod.stock < v_qty then
      raise exception 'OUT_OF_STOCK:%', prod.name_fr;
    end if;

    -- if the garment comes in sizes, one of them must have been chosen:
    -- substituting a default here would deliver a size nobody asked for
    v_size := coalesce(line->>'size', '');
    if array_length(prod.sizes, 1) > 0 and not (v_size = any (prod.sizes)) then
      raise exception 'INVALID_SIZE';
    end if;

    update products set stock = stock - v_qty where id = prod.id;

    v_sub := v_sub + prod.price * v_qty;
    clean := clean || jsonb_build_object(
      'product_id', prod.id,
      'name_fr', prod.name_fr, 'name_ar', prod.name_ar, 'name_en', prod.name_en,
      'size',  v_size,
      'qty',   v_qty,
      'price', prod.price,
      'photo', coalesce(prod.photos[1], '')
    );
  end loop;

  insert into orders (customer_name, phone, address, zone,
                      delivery_fee, items, subtotal, total, status)
  values (p_name, p_phone, p_address, p_zone,
          v_fee, clean, v_sub, v_sub + v_fee, 'new')
  returning id into v_id;

  return jsonb_build_object(
    'id', v_id, 'subtotal', v_sub, 'delivery_fee', v_fee, 'total', v_sub + v_fee
  );
end $$;

revoke all on function public.place_order(text,text,text,text,jsonb) from public;
grant execute on function public.place_order(text,text,text,text,jsonb) to anon, authenticated;

-- ============================================================
-- TRACKING AN ORDER
--
-- Customers still cannot read the orders table — that would expose every
-- name, phone and address in the shop. They call this instead, which returns
-- one order only when the order number AND the phone that placed it match.
-- Knowing a number alone is not enough.
--
-- The phone is compared on its last 8 digits so that 0555 12 34 56 matches
-- +213555123456: the customer should not have to remember which format they
-- typed. Name and address are deliberately NOT returned; the customer already
-- knows them, so there is nothing to gain by echoing them to a lucky guess.
-- ============================================================
create or replace function public.track_order(p_id bigint, p_phone text)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  o      orders%rowtype;
  digits text;
begin
  digits := regexp_replace(coalesce(p_phone, ''), '\D', '', 'g');
  if p_id is null or length(digits) < 8 then
    raise exception 'NOT_FOUND';
  end if;

  select * into o from orders
  where id = p_id
    and right(regexp_replace(phone, '\D', '', 'g'), 8) = right(digits, 8);

  if not found then
    raise exception 'NOT_FOUND';
  end if;

  return jsonb_build_object(
    'id',           o.id,
    'status',       o.status,
    'created_at',   o.created_at,
    'zone',         o.zone,
    'subtotal',     o.subtotal,
    'delivery_fee', o.delivery_fee,
    'total',        o.total,
    'items',        o.items
  );
end $$;

revoke all on function public.track_order(bigint, text) from public;
grant execute on function public.track_order(bigint, text) to anon, authenticated;

-- Cancelling an order puts the items back on the shelf.
create or replace function public.restock_cancelled_order()
returns trigger
language plpgsql security definer set search_path = public, pg_temp
as $$
declare line jsonb;
begin
  if new.status = 'cancelled' and old.status <> 'cancelled' then
    for line in select * from jsonb_array_elements(new.items) loop
      update products set stock = stock + (line->>'qty')::int
      where id = (line->>'product_id')::bigint;
    end loop;
  end if;
  return new;
end $$;

drop trigger if exists orders_restock on orders;
create trigger orders_restock
  after update of status on orders
  for each row execute function public.restock_cancelled_order();


-- ============================================================
-- Row Level Security
-- ============================================================
alter table categories enable row level security;
alter table products   enable row level security;
alter table orders     enable row level security;
alter table settings   enable row level security;

-- remove the policies from earlier versions of this file
drop policy if exists "public read categories" on categories;
drop policy if exists "public read products"   on products;
drop policy if exists "public read settings"   on settings;
drop policy if exists "public place orders"    on orders;
drop policy if exists "owner all categories"   on categories;
drop policy if exists "owner all products"     on products;
drop policy if exists "owner all orders"       on orders;
drop policy if exists "owner all settings"     on settings;

drop policy if exists "read categories"        on categories;
drop policy if exists "owner writes categories" on categories;
drop policy if exists "read active products"   on products;
drop policy if exists "owner writes products"  on products;
drop policy if exists "read public settings"   on settings;
drop policy if exists "owner writes settings"  on settings;
drop policy if exists "owner only orders"      on orders;

-- Visitors: read the catalogue, and nothing else.
create policy "read categories" on categories
  for select using (true);

-- hidden products stay hidden even for someone calling the API by hand
create policy "read active products" on products
  for select using (active = true);

-- only the store name/phone and the delivery zones are public
create policy "read public settings" on settings
  for select using (key in ('store', 'zones'));

-- Orders: no public read, no public write. Visitors go through place_order().
create policy "owner only orders" on orders
  for all using (public.is_owner()) with check (public.is_owner());

-- The owner — and only the owner — manages the rest.
create policy "owner writes categories" on categories
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner writes products" on products
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner writes settings" on settings
  for all using (public.is_owner()) with check (public.is_owner());


-- ============================================================
-- Storage (product photos)
-- ============================================================
insert into storage.buckets (id, name, public) values ('products', 'products', true)
on conflict (id) do nothing;

drop policy if exists "public read product photos" on storage.objects;
drop policy if exists "owner uploads photos" on storage.objects;
drop policy if exists "owner updates photos" on storage.objects;
drop policy if exists "owner deletes photos" on storage.objects;

create policy "public read product photos" on storage.objects
  for select using (bucket_id = 'products');
create policy "owner uploads photos" on storage.objects
  for insert with check (bucket_id = 'products' and public.is_owner());
create policy "owner updates photos" on storage.objects
  for update using (bucket_id = 'products' and public.is_owner());
create policy "owner deletes photos" on storage.objects
  for delete using (bucket_id = 'products' and public.is_owner());


-- ============================================================
-- LAST STEP — create the owner account
--
-- Supabase Dashboard > Authentication > Users > Add user
--   email: your@email.com   password: choose a strong one
--   tick "Auto Confirm User"
-- The first account created is automatically the owner. Use the same
-- credentials to log into admin.html.
--
-- Then close the door behind you:
--   Authentication > Sign In / Providers > Email > turn OFF "Allow new users
--   to sign up". Without this, strangers can still create (powerless) accounts.
--
-- To check it worked:  select * from owners;   -- should show exactly one row
-- ============================================================
