-- ============================================================
-- GOAT meubles — Supabase schema (tables, security, order logic)
-- Paste this whole file into: Supabase Dashboard > SQL Editor > New query > Run
--
-- Safe to run again later: policies and functions are dropped and recreated.
--
-- IMPORTANT — this file is the real security of the site.
-- The website is static, so the browser talks to Postgres directly and anyone
-- can call the API without loading your pages. Nothing in js/ protects data;
-- the rules below do.
-- ============================================================

-- ---------- CATEGORIES ----------
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name_fr text not null,
  name_ar text not null,
  name_en text not null,
  image text not null default '',        -- showcase tile photo (Storage URL)
  sort int not null default 0,
  created_at timestamptz not null default now()
);
-- v1.1 upgrade for older installs
alter table categories add column if not exists image text not null default '';

-- ---------- PRODUCTS ----------
create table if not exists products (
  id bigint generated by default as identity primary key,
  name_fr text not null,
  name_ar text not null,
  name_en text not null,
  description_fr text default '',
  description_ar text default '',
  description_en text default '',
  price numeric not null check (price >= 0),
  compare_at_price numeric check (compare_at_price >= 0),
  photos text[] not null default '{}',
  sizes text[] not null default '{"S","M","L","XL","XXL"}',
  category_id bigint references categories(id) on delete set null,
  stock int not null default 0 check (stock >= 0),
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------- ORDERS (cash on delivery only) ----------
create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null,
  zone text not null,                -- delivery zone (wilaya / area)
  delivery_fee numeric not null default 0,
  items jsonb not null,              -- [{product_id, name_*, size, price, qty, photo}]
  subtotal numeric not null,
  total numeric not null,
  status text not null default 'new' -- new | confirmed | shipped | delivered | cancelled
        check (status in ('new','confirmed','shipped','delivered','cancelled')),
  discount numeric not null default 0, -- promo-code amount deducted (v1.1)
  promo_code text not null default '', -- code that was applied, '' if none (v1.1)
  -- 'home' = à domicile, 'desk' = stopdesk (collected from the agency) (v1.3)
  delivery_type text not null default 'home'
        check (delivery_type in ('home','desk')),
  -- the courier's own parcel number, typed in by the owner once the parcel is
  -- handed over. Without it the tracking page can only ever show an internal
  -- status, and nobody can look the parcel up with Yalidine / ZR / Noest.
  carrier text not null default '',
  tracking_number text not null default '',
  created_at timestamptz not null default now()
);
-- v1.1 upgrade for older installs
alter table orders add column if not exists discount numeric not null default 0;
alter table orders add column if not exists promo_code text not null default '';
-- v1.3
alter table orders add column if not exists delivery_type text not null default 'home';
alter table orders add column if not exists carrier text not null default '';
alter table orders add column if not exists tracking_number text not null default '';
do $$ begin
  alter table orders add constraint orders_delivery_type_check
    check (delivery_type in ('home','desk'));
exception when duplicate_object then null;
end $$;

create index if not exists orders_created_at_idx on orders (created_at desc);
create index if not exists orders_phone_idx on orders (phone, created_at desc);

-- ---------- SETTINGS (store name, phone, delivery zones) ----------
create table if not exists settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into settings (key, value) values
  ('store', '{"name":"GOAT meubles","phone":"","email":""}'),
  ('zones', '[]'),
  ('promo', '{"active":false,"percent":0,"label_fr":"","label_ar":"","label_en":""}'),
  ('free_delivery_from', 'null')
on conflict (key) do nothing;

-- ---------- THE 58 WILAYAS ----------
-- Algerian delivery is priced per wilaya and in two flavours: `desk` is
-- stopdesk, where the customer collects from the courier's agency, and `home`
-- is delivery to the door. Stopdesk is markedly cheaper and a large share of
-- customers will only order at that price, so a shop offering just one of them
-- is turning orders away.
--
-- The figures below are starting values, not real tariffs — set yours in the
-- dashboard (Zones de livraison). Re-running this file MERGES: a wilaya you
-- have already priced keeps your numbers, missing ones are added. Nothing you
-- typed is overwritten.
--
-- Pre-v1.3 installs had one flat `fee` per zone, which was a home-delivery
-- price; it is carried over to `home`, and `desk` starts from the default
-- because those shops never had a stopdesk price to keep.
do $$
declare
  canonical jsonb := '[{"code":1,"name":"Adrar","desk":900,"home":1400},{"code":2,"name":"Chlef","desk":450,"home":650},{"code":3,"name":"Laghouat","desk":500,"home":800},{"code":4,"name":"Oum El Bouaghi","desk":500,"home":750},{"code":5,"name":"Batna","desk":500,"home":750},{"code":6,"name":"Béjaïa","desk":450,"home":650},{"code":7,"name":"Biskra","desk":550,"home":850},{"code":8,"name":"Béchar","desk":800,"home":1200},{"code":9,"name":"Blida","desk":400,"home":500},{"code":10,"name":"Bouira","desk":450,"home":650},{"code":11,"name":"Tamanrasset","desk":900,"home":1600},{"code":12,"name":"Tébessa","desk":500,"home":800},{"code":13,"name":"Tlemcen","desk":450,"home":700},{"code":14,"name":"Tiaret","desk":500,"home":750},{"code":15,"name":"Tizi Ouzou","desk":450,"home":650},{"code":16,"name":"Alger","desk":400,"home":500},{"code":17,"name":"Djelfa","desk":500,"home":800},{"code":18,"name":"Jijel","desk":450,"home":700},{"code":19,"name":"Sétif","desk":450,"home":700},{"code":20,"name":"Saïda","desk":500,"home":750},{"code":21,"name":"Skikda","desk":450,"home":700},{"code":22,"name":"Sidi Bel Abbès","desk":450,"home":700},{"code":23,"name":"Annaba","desk":450,"home":700},{"code":24,"name":"Guelma","desk":450,"home":700},{"code":25,"name":"Constantine","desk":450,"home":650},{"code":26,"name":"Médéa","desk":450,"home":650},{"code":27,"name":"Mostaganem","desk":450,"home":700},{"code":28,"name":"M''Sila","desk":500,"home":750},{"code":29,"name":"Mascara","desk":450,"home":700},{"code":30,"name":"Ouargla","desk":700,"home":1100},{"code":31,"name":"Oran","desk":450,"home":650},{"code":32,"name":"El Bayadh","desk":700,"home":1100},{"code":33,"name":"Illizi","desk":900,"home":1600},{"code":34,"name":"Bordj Bou Arréridj","desk":450,"home":700},{"code":35,"name":"Boumerdès","desk":400,"home":550},{"code":36,"name":"El Tarf","desk":500,"home":750},{"code":37,"name":"Tindouf","desk":900,"home":1600},{"code":38,"name":"Tissemsilt","desk":500,"home":800},{"code":39,"name":"El Oued","desk":700,"home":1100},{"code":40,"name":"Khenchela","desk":500,"home":800},{"code":41,"name":"Souk Ahras","desk":500,"home":800},{"code":42,"name":"Tipaza","desk":400,"home":550},{"code":43,"name":"Mila","desk":450,"home":700},{"code":44,"name":"Aïn Defla","desk":450,"home":700},{"code":45,"name":"Naâma","desk":700,"home":1100},{"code":46,"name":"Aïn Témouchent","desk":450,"home":700},{"code":47,"name":"Ghardaïa","desk":650,"home":1000},{"code":48,"name":"Relizane","desk":450,"home":700},{"code":49,"name":"Timimoun","desk":900,"home":1500},{"code":50,"name":"Bordj Badji Mokhtar","desk":1000,"home":1800},{"code":51,"name":"Ouled Djellal","desk":600,"home":900},{"code":52,"name":"Béni Abbès","desk":800,"home":1300},{"code":53,"name":"In Salah","desk":900,"home":1600},{"code":54,"name":"In Guezzam","desk":1000,"home":1800},{"code":55,"name":"Touggourt","desk":700,"home":1100},{"code":56,"name":"Djanet","desk":1000,"home":1800},{"code":57,"name":"El M''Ghair","desk":700,"home":1100},{"code":58,"name":"El Meniaa","desk":800,"home":1200}]'::jsonb;
  current_zones jsonb;
  merged jsonb := '[]'::jsonb;
  w jsonb;
  old jsonb;
begin
  select value into current_zones from settings where key = 'zones';
  current_zones := coalesce(current_zones, '[]'::jsonb);

  for w in select * from jsonb_array_elements(canonical) loop
    select z into old
    from jsonb_array_elements(current_zones) z
    where lower(btrim(z->>'name')) = lower(btrim(w->>'name'))
    limit 1;

    merged := merged || jsonb_build_object(
      'code', w->'code',
      'name', w->>'name',
      -- an existing home price wins; before v1.3 that price was called 'fee'
      'home', coalesce(old->'home', old->'fee', w->'home'),
      'desk', coalesce(old->'desk', w->'desk')
    );
  end loop;

  update settings set value = merged, updated_at = now() where key = 'zones';
end $$;

-- ---------- PROMO CODES (v1.1) ----------
-- Not readable by the public: customers only learn a code's discount by
-- entering it, and place_order() re-validates it anyway. Codes like
-- BIENVENUE10 give a percentage off; min_order is optional.
create table if not exists promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  percent int not null check (percent between 1 and 90),
  min_order numeric not null default 0 check (min_order >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Upgrade older installs: identity columns must accept an explicit id so that
-- the admin panel's "save" (an upsert, which sends the id) can update a row.
alter table categories alter column id set generated by default;
alter table products   alter column id set generated by default;
alter table orders     alter column id set generated by default;


-- ============================================================
-- WHO IS THE OWNER
--
-- "logged in" is not the same as "the owner": anyone can sign up with the
-- public anon key. Ownership is an explicit list of one.
-- ============================================================
create table if not exists owners (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table owners enable row level security;
-- deliberately no policies: this table is unreachable through the public API

-- ============================================================
-- ALGERIAN PHONE NUMBERS
--
-- A cash-on-delivery order is worth nothing without a number the driver can
-- ring: a bad one costs the ad click that produced it AND the courier trip
-- that delivers nothing. The old check accepted any 8+ characters made of
-- digits, spaces and dashes, so "123456789" passed.
--
-- A real Algerian mobile is 0 followed by 5, 6 or 7 and eight more digits.
-- The same number arrives written half a dozen ways — 0555 12 34 56,
-- +213 555 123 456, 00213555123456 — so strip it to digits, peel off the
-- international prefixes and the trunk 0, and check what is left. Returns the
-- canonical 0XXXXXXXXX form, or null when it is not a mobile at all, so every
-- order is stored in one shape and the CSV handed to the courier is uniform.
-- ============================================================
create or replace function public.dz_phone(p_phone text)
returns text
language sql immutable
as $$
  select case
    when d ~ '^[567][0-9]{8}$' then '0' || d
    else null
  end
  from (
    select regexp_replace(
             regexp_replace(
               regexp_replace(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g'),
                              '^00', ''),
               '^213', ''),
             '^0', '') as d
  ) t
$$;

create or replace function public.is_owner()
returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$ select exists (select 1 from owners where user_id = auth.uid()) $$;

-- The FIRST account created becomes the owner. Every later signup gets nothing.
create or replace function public.claim_ownership()
returns trigger
language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  insert into owners (user_id)
  select new.id where not exists (select 1 from owners);
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.claim_ownership();


-- ============================================================
-- PLACING AN ORDER
--
-- Visitors cannot insert into `orders` directly — if they could, they would
-- also choose the prices. They call this function instead, which rebuilds the
-- basket from the real products table and ignores every number the browser
-- sent. Stock is reserved in the same transaction.
--
-- v1.1 pricing, all decided here and nowhere else:
--   1. a global sale (settings key 'promo') lowers every unit price
--   2. a promo code (promo_codes, passed as p_promo_code) takes a further
--      percentage off the discounted subtotal
--   3. free delivery over a threshold (settings key 'free_delivery_from')
--      zeroes the zone fee
-- ============================================================
-- v1.3 adds p_delivery_type: 'home' (à domicile) or 'desk' (stopdesk), which
-- selects which of the wilaya's two prices applies.
--
-- Every signature change creates a SECOND function beside the old one, because
-- `create or replace` matches on arguments. PostgREST then sees two candidates
-- and refuses every call with PGRST203 — which means no orders at all, silently,
-- until someone notices. Drop every previous shape first. Harmless on a fresh
-- install.
drop function if exists public.place_order(text, text, text, text, jsonb);
drop function if exists public.place_order(text, text, text, text, jsonb, text);

create or replace function public.place_order(
  p_name    text,
  p_phone   text,
  p_address text,
  p_zone    text,
  p_items   jsonb,
  p_promo_code text default '',
  p_delivery_type text default 'home'
)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  line  jsonb;
  prod  products%rowtype;
  v_pid bigint;
  v_qty int;
  v_size text;
  clean jsonb := '[]'::jsonb;
  v_sub numeric := 0;
  v_fee numeric;
  v_id  bigint;
  v_promo_pct numeric := 0;
  v_unit numeric;
  v_code promo_codes%rowtype;
  v_discount numeric := 0;
  v_applied_code text := '';
  v_free_from numeric;
begin
  p_name    := left(btrim(coalesce(p_name,    '')), 120);
  p_phone   := left(btrim(coalesce(p_phone,   '')), 30);
  p_address := left(btrim(coalesce(p_address, '')), 400);
  p_zone    := left(btrim(coalesce(p_zone,    '')), 80);
  p_promo_code := upper(left(btrim(coalesce(p_promo_code, '')), 40));
  p_delivery_type := lower(btrim(coalesce(p_delivery_type, 'home')));
  if p_delivery_type not in ('home', 'desk') then
    p_delivery_type := 'home';
  end if;

  -- stopdesk means the customer collects from the courier's agency, so a street
  -- address is not required — the wilaya is. Home delivery needs both.
  if p_name = '' or p_phone = ''
     or (p_delivery_type = 'home' and p_address = '') then
    raise exception 'MISSING_FIELDS';
  end if;

  -- one canonical 0XXXXXXXXX, or not an Algerian mobile at all
  p_phone := dz_phone(p_phone);
  if p_phone is null then
    raise exception 'INVALID_PHONE';
  end if;

  -- light anti-spam: the form is open to the whole internet. Comparing the
  -- normalised number matters here — otherwise the same phone typed three
  -- different ways counts as three different customers.
  if (select count(*) from orders
      where dz_phone(phone) = p_phone
        and created_at > now() - interval '1 hour') >= 5 then
    raise exception 'TOO_MANY_ORDERS';
  end if;

  -- v1.5: a daily ceiling too. Five an hour still allowed a determined prank
  -- to file a hundred orders overnight, and every one of them is a courier
  -- rolling out to a dead phone.
  if (select count(*) from orders
      where dz_phone(phone) = p_phone
        and created_at > now() - interval '24 hours') >= 10 then
    raise exception 'TOO_MANY_ORDERS_TODAY';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'INVALID_CART';
  end if;

  -- global sale percentage, 0 when absent or switched off
  select coalesce((value->>'percent')::numeric, 0) into v_promo_pct
  from settings
  where key = 'promo' and coalesce((value->>'active')::boolean, false);
  if v_promo_pct is null then v_promo_pct := 0; end if;
  v_promo_pct := least(greatest(v_promo_pct, 0), 90);   -- trust no setting blindly

  -- free delivery threshold, null when unused
  select nullif(value, 'null'::jsonb)::numeric into v_free_from
  from settings where key = 'free_delivery_from';
  if v_free_from is null then v_free_from := 0; end if;

  -- The delivery fee comes from settings, never from the browser, and which of
  -- the wilaya's two prices applies is decided here too. `fee` is the pre-v1.3
  -- single price, kept as a fallback so an install that has not re-run this
  -- file still takes orders instead of failing on UNKNOWN_ZONE.
  select coalesce(
           (z->>(case when p_delivery_type = 'desk' then 'desk' else 'home' end))::numeric,
           (z->>'home')::numeric,
           (z->>'fee')::numeric
         ) into v_fee
  from settings s, jsonb_array_elements(s.value) z
  where s.key = 'zones' and z->>'name' = p_zone
  limit 1;
  if v_fee is null then
    raise exception 'UNKNOWN_ZONE';
  end if;

  for line in select * from jsonb_array_elements(p_items) loop
    -- the browser may send anything at all here, including text where a
    -- number belongs, so a failed cast is just a rejected order
    begin
      v_pid := (line->>'product_id')::bigint;
      v_qty := floor((line->>'qty')::numeric)::int;
    exception when others then
      raise exception 'INVALID_CART';
    end;

    if v_qty is null or v_qty < 1 or v_qty > 20 then
      raise exception 'INVALID_CART';
    end if;

    select * into prod from products
    where id = v_pid and active = true
    for update;
    if not found then
      raise exception 'PRODUCT_UNAVAILABLE';
    end if;
    if prod.stock < v_qty then
      raise exception 'OUT_OF_STOCK:%', prod.name_fr;
    end if;

    -- if the garment comes in sizes, one of them must have been chosen:
    -- substituting a default here would deliver a size nobody asked for
    v_size := coalesce(line->>'size', '');
    if array_length(prod.sizes, 1) > 0 and not (v_size = any (prod.sizes)) then
      raise exception 'INVALID_SIZE';
    end if;

    update products set stock = stock - v_qty where id = prod.id;

    -- the price the customer pays: the shelf price with the global sale
    -- applied. base_price keeps what it was before the sale so the receipt
    -- and the admin panel can show what was saved.
    v_unit := round(prod.price * (100 - v_promo_pct) / 100, 2);
    v_sub := v_sub + v_unit * v_qty;
    clean := clean || jsonb_build_object(
      'product_id', prod.id,
      'name_fr', prod.name_fr, 'name_ar', prod.name_ar, 'name_en', prod.name_en,
      'size',  v_size,
      'qty',   v_qty,
      'price', v_unit,
      'base_price', prod.price,
      'photo', coalesce(prod.photos[1], '')
    );
  end loop;

  -- promo code: validated against the table, never against what the browser
  -- claimed while previewing the total
  if p_promo_code <> '' then
    select * into v_code from promo_codes
    where upper(code) = p_promo_code and active;
    if not found then
      raise exception 'INVALID_PROMO';
    end if;
    if v_sub < v_code.min_order then
      raise exception 'PROMO_MIN_ORDER';
    end if;
    v_discount := round(v_sub * v_code.percent / 100, 2);
    v_applied_code := v_code.code;
  end if;

  -- Free delivery above the threshold, measured on what the customer actually
  -- pays for the goods — so after the promo code, not before it. The checkout
  -- preview (updateTotals() in js/checkout.js) compares the same
  -- after-discount figure; if the two ever disagree the customer is quoted one
  -- delivery fee and charged another.
  if v_free_from > 0 and (v_sub - v_discount) >= v_free_from then
    v_fee := 0;
  end if;

  -- v1.5: identical basket from the same phone inside 24h is a double-click
  -- or a replayed prank — two real customers never order the exact same cart
  -- twice from one number. Compared as multisets, so line order is irrelevant.
  if exists (
    select 1
    from orders o
    where dz_phone(o.phone) = p_phone
      and o.created_at > now() - interval '24 hours'
      and jsonb_array_length(o.items) = jsonb_array_length(clean)
      and not exists (
        select 1
        from jsonb_array_elements(clean) c
        left join jsonb_array_elements(o.items) x
          on x->>'product_id' = c->>'product_id'
         and coalesce(x->>'size', '') = coalesce(c->>'size', '')
         and (x->>'qty')::int = (c->>'qty')::int
        where x is null
      )
  ) then
    raise exception 'DUPLICATE_ORDER';
  end if;

  insert into orders (customer_name, phone, address, zone,
                      delivery_fee, items, subtotal, discount, promo_code,
                      total, status, delivery_type)
  values (p_name, p_phone, p_address, p_zone,
          v_fee, clean, v_sub, v_discount, v_applied_code,
          v_sub - v_discount + v_fee, 'new', p_delivery_type)
  returning id into v_id;

  return jsonb_build_object(
    'id', v_id, 'subtotal', v_sub, 'discount', v_discount,
    'promo_code', v_applied_code, 'delivery_fee', v_fee,
    'delivery_type', p_delivery_type, 'phone', p_phone,
    'total', v_sub - v_discount + v_fee
  );
end $$;

revoke all on function public.place_order(text,text,text,text,jsonb,text,text) from public;
grant execute on function public.place_order(text,text,text,text,jsonb,text,text) to anon, authenticated;

-- ============================================================
-- PROMO CODE PREVIEW
--
-- Lets the checkout page show "−10%" the moment a code is typed, without
-- making the promo_codes table readable. Only the code's percentage comes
-- back; the price the customer pays is still decided by place_order().
-- ============================================================
create or replace function public.check_promo(p_code text, p_sub numeric)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  c promo_codes%rowtype;
begin
  select * into c from promo_codes
  where upper(code) = upper(left(btrim(coalesce(p_code, '')), 40)) and active;
  if not found then
    raise exception 'INVALID_PROMO';
  end if;
  if coalesce(p_sub, 0) < c.min_order then
    raise exception 'PROMO_MIN_ORDER';
  end if;
  return jsonb_build_object('code', c.code, 'percent', c.percent, 'min_order', c.min_order);
end $$;

revoke all on function public.check_promo(text, numeric) from public;
grant execute on function public.check_promo(text, numeric) to anon, authenticated;

-- ============================================================
-- TRACKING AN ORDER
--
-- Customers still cannot read the orders table — that would expose every
-- name, phone and address in the shop. They call this instead, which returns
-- one order only when the order number AND the phone that placed it match.
-- Knowing a number alone is not enough.
--
-- The phone is compared on its last 8 digits so that 0555 12 34 56 matches
-- +213555123456: the customer should not have to remember which format they
-- typed. Name and address are deliberately NOT returned; the customer already
-- knows them, so there is nothing to gain by echoing them to a lucky guess.
-- ============================================================
create or replace function public.track_order(p_id bigint, p_phone text)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  o      orders%rowtype;
  digits text;
begin
  digits := regexp_replace(coalesce(p_phone, ''), '\D', '', 'g');
  if p_id is null or length(digits) < 8 then
    raise exception 'NOT_FOUND';
  end if;

  select * into o from orders
  where id = p_id
    and right(regexp_replace(phone, '\D', '', 'g'), 8) = right(digits, 8);

  if not found then
    raise exception 'NOT_FOUND';
  end if;

  return jsonb_build_object(
    'id',            o.id,
    'status',        o.status,
    'created_at',    o.created_at,
    'zone',          o.zone,
    'subtotal',      o.subtotal,
    'delivery_fee',  o.delivery_fee,
    'total',         o.total,
    'items',         o.items,
    -- so the customer sees where to collect, and can follow the parcel with
    -- the courier directly instead of ringing the shop to ask
    'delivery_type', o.delivery_type,
    'carrier',       o.carrier,
    'tracking_number', o.tracking_number
  );
end $$;

revoke all on function public.track_order(bigint, text) from public;
grant execute on function public.track_order(bigint, text) to anon, authenticated;

-- Cancelling an order puts the items back on the shelf.
create or replace function public.restock_cancelled_order()
returns trigger
language plpgsql security definer set search_path = public, pg_temp
as $$
declare line jsonb;
begin
  if new.status = 'cancelled' and old.status <> 'cancelled' then
    for line in select * from jsonb_array_elements(new.items) loop
      update products set stock = stock + (line->>'qty')::int
      where id = (line->>'product_id')::bigint;
    end loop;
  end if;
  return new;
end $$;

drop trigger if exists orders_restock on orders;
create trigger orders_restock
  after update of status on orders
  for each row execute function public.restock_cancelled_order();


-- ============================================================
-- Row Level Security
-- ============================================================
alter table categories enable row level security;
alter table products   enable row level security;
alter table orders     enable row level security;
alter table settings   enable row level security;
alter table promo_codes enable row level security;
-- no policy on promo_codes for anon: the table is invisible to visitors;
-- check_promo() and place_order() are the only public doors

-- remove the policies from earlier versions of this file
drop policy if exists "public read categories" on categories;
drop policy if exists "public read products"   on products;
drop policy if exists "public read settings"   on settings;
drop policy if exists "public place orders"    on orders;
drop policy if exists "owner all categories"   on categories;
drop policy if exists "owner all products"     on products;
drop policy if exists "owner all orders"       on orders;
drop policy if exists "owner all settings"     on settings;

drop policy if exists "read categories"        on categories;
drop policy if exists "owner writes categories" on categories;
drop policy if exists "read active products"   on products;
drop policy if exists "owner writes products"  on products;
drop policy if exists "read public settings"   on settings;
drop policy if exists "owner writes settings"  on settings;
drop policy if exists "owner only orders"      on orders;
drop policy if exists "owner writes promo codes" on promo_codes;

-- Visitors: read the catalogue, and nothing else.
create policy "read categories" on categories
  for select using (true);

-- hidden products stay hidden even for someone calling the API by hand
create policy "read active products" on products
  for select using (active = true);

-- only the storefront-facing settings are public: shop identity, delivery
-- zones, the active global sale and the free-delivery threshold
create policy "read public settings" on settings
  for select using (key in ('store', 'zones', 'promo', 'free_delivery_from'));

-- Orders: no public read, no public write. Visitors go through place_order().
create policy "owner only orders" on orders
  for all using (public.is_owner()) with check (public.is_owner());

-- The owner — and only the owner — manages the rest.
create policy "owner writes categories" on categories
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner writes products" on products
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner writes settings" on settings
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner writes promo codes" on promo_codes
  for all using (public.is_owner()) with check (public.is_owner());


-- ============================================================
-- Storage (product photos, category showcase tiles)
-- ============================================================
insert into storage.buckets (id, name, public) values ('products', 'products', true)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('categories', 'categories', true)
on conflict (id) do nothing;

drop policy if exists "public read product photos" on storage.objects;
drop policy if exists "owner uploads photos" on storage.objects;
drop policy if exists "owner updates photos" on storage.objects;
drop policy if exists "owner deletes photos" on storage.objects;
drop policy if exists "public read category photos" on storage.objects;

create policy "public read product photos" on storage.objects
  for select using (bucket_id = 'products');
create policy "public read category photos" on storage.objects
  for select using (bucket_id = 'categories');
create policy "owner uploads photos" on storage.objects
  for insert with check (bucket_id in ('products', 'categories') and public.is_owner());
create policy "owner updates photos" on storage.objects
  for update using (bucket_id in ('products', 'categories') and public.is_owner());
create policy "owner deletes photos" on storage.objects
  for delete using (bucket_id in ('products', 'categories') and public.is_owner());


-- ============================================================
-- LAST STEP — create the owner account
--
-- Supabase Dashboard > Authentication > Users > Add user
--   email: your@email.com   password: choose a strong one
--   tick "Auto Confirm User"
-- The first account created is automatically the owner. Use the same
-- credentials to log into admin.html.
--
-- Then close the door behind you:
--   Authentication > Sign In / Providers > Email > turn OFF "Allow new users
--   to sign up". Without this, strangers can still create (powerless) accounts.
--
-- To check it worked:  select * from owners;   -- should show exactly one row
-- ============================================================


-- ============================================================
-- v1.5 — CUSTOMER REVIEWS
--
-- Social proof is the strongest converter a COD shop can add: the buyer
-- cannot touch the product, so other buyers' words carry the sale.
--
-- Flow: anyone may submit (insert), nothing is public until the owner
-- approves it. This keeps prank and competitor reviews off the page without
-- making honest customers wait for an account they will never create.
-- ============================================================

create table if not exists reviews (
  id bigint generated always as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  name text not null,
  rating int not null check (rating between 1 and 5),
  body text not null default '',
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists reviews_product_idx on reviews(product_id) where approved;
create index if not exists reviews_pending_idx on reviews(created_at) where not approved;

alter table reviews enable row level security;

drop policy if exists "anyone may submit a review" on reviews;
drop policy if exists "approved reviews are public" on reviews;
drop policy if exists "owner sees all reviews" on reviews;
drop policy if exists "owner manages reviews" on reviews;
drop policy if exists "owner deletes reviews" on reviews;

-- submission needs no account; length limits keep the abuse surface small.
-- Approval still gates what becomes public, so spam costs the owner one click.
create policy "anyone may submit a review" on reviews
  for insert to anon, authenticated
  with check (char_length(name) between 2 and 60 and char_length(body) <= 600);

create policy "approved reviews are public" on reviews
  for select using (approved);

create policy "owner sees all reviews" on reviews
  for select to authenticated using (public.is_owner());

create policy "owner manages reviews" on reviews
  for update to authenticated using (public.is_owner()) with check (public.is_owner());

create policy "owner deletes reviews" on reviews
  for delete to authenticated using (public.is_owner());

-- One aggregate row per product for cards and product pages: average and
-- count over APPROVED reviews only. Security definer so it can read the table
-- without opening it up; takes a slice of ids or all products when null.
create or replace function public.review_summary(p_ids bigint[] default null)
returns table (product_id bigint, avg_rating numeric, review_count bigint)
language sql stable security definer set search_path = public as $$
  select r.product_id, round(avg(r.rating)::numeric, 1), count(*)
  from reviews r
  where r.approved
    and (p_ids is null or r.product_id = any (p_ids))
  group by r.product_id;
$$;

revoke all on function public.review_summary(bigint[]) from public;
grant execute on function public.review_summary(bigint[]) to anon, authenticated;

-- v1.5.1 — adjustable review baseline
-- The owner may seed a starting count/average (a shop that sold for years
-- before launching the site should not start at zero credibility). Stored as
-- a public settings row: {"count": 15, "avg": 4.6}. Real reviews are blended
-- with it, never replaced by it.
insert into settings (key, value) values ('reviews_baseline', '{"count": 0, "avg": 0}')
on conflict (key) do nothing;

drop policy if exists "read public settings" on settings;
create policy "read public settings" on settings
  for select using (key in ('store', 'zones', 'promo', 'free_delivery_from', 'reviews_baseline'));


-- ============================================================
-- v1.6 — ABANDONED CHECKOUT LEADS + RETURN STATUS
--
-- A cart is browser-local storage: when someone fills their name and phone
-- but leaves before pressing Commander, that lead used to vanish. This table
-- keeps it — the owner sees who to call back. Public writes only (no reads),
-- so the table leaks nothing even though the whole internet can write to it.
-- ============================================================

create table if not exists checkout_leads (
  id bigint generated always as identity primary key,
  phone text not null,
  name text not null default '',
  zone text not null default '',
  items jsonb not null default '[]',
  total numeric not null default 0,
  recovered boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists leads_open_idx on checkout_leads(created_at) where not recovered;

alter table checkout_leads enable row level security;

drop policy if exists "anyone may leave a lead" on checkout_leads;
drop policy if exists "owner reads leads" on checkout_leads;
drop policy if exists "owner manages leads" on checkout_leads;
drop policy if exists "owner deletes leads" on checkout_leads;

create policy "anyone may leave a lead" on checkout_leads
  for insert to anon, authenticated
  with check (char_length(phone) <= 20);

create policy "owner reads leads" on checkout_leads
  for select to authenticated using (public.is_owner());

create policy "owner manages leads" on checkout_leads
  for update to authenticated using (public.is_owner()) with check (public.is_owner());

create policy "owner deletes leads" on checkout_leads
  for delete to authenticated using (public.is_owner());

-- orders may come back: refused at the door, damaged in transit, exchanged.
-- The status CHECK on orders only knows five states; widen it to accept
-- 'returned' (the constraint arrived unnamed in v1.0, so find it by column).
do $$
declare c text;
begin
  select conname into c from pg_constraint
   where conrelid = 'orders'::regclass and contype = 'c'
     and pg_get_constraintdef(oid) like '%status%';
  if c is not null then
    execute format('alter table orders drop constraint %I', c);
  end if;
end $$;
alter table orders add constraint orders_status_chk
  check (status in ('new','confirmed','shipped','delivered','cancelled','returned'));
