-- ============================================================
-- 35 Relax Confort products — paste into Supabase SQL Editor → Run
-- Columns: name_fr, name_en, name_ar, description_fr, price,
--   compare_at_price, photos, sizes, category_id, stock, featured, active
-- ============================================================

DO $$
DECLARE
  cat_poufs bigint; cat_matelas bigint; cat_surmatelas bigint;
  cat_literie bigint; cat_bain bigint; cat_oreillers bigint;
BEGIN
  SELECT id INTO cat_poufs FROM categories WHERE name_fr = 'Poufs & Beanbags' LIMIT 1;
  SELECT id INTO cat_matelas FROM categories WHERE name_fr = 'Matelas' LIMIT 1;
  SELECT id INTO cat_surmatelas FROM categories WHERE name_fr = 'Surmatelas' LIMIT 1;
  SELECT id INTO cat_literie FROM categories WHERE name_fr = 'Literie' LIMIT 1;
  SELECT id INTO cat_bain FROM categories WHERE name_fr = 'Textiles de Bain' LIMIT 1;
  SELECT id INTO cat_oreillers FROM categories WHERE name_fr = 'Oreillers & Coussins' LIMIT 1;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'AURA%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('AURA – L''Éclat du Confort','AURA – The Brilliance of Comfort','أورا – بريق الراحة','L''AURA offre l''équilibre parfait entre la souplesse d''un pouf et le maintien d''un vrai fauteuil.',15900,19500,ARRAY['/assets/products/aura_1.jpg','/assets/products/aura_2.jpg','/assets/products/aura_3.jpg'],ARRAY['Beige','Bleu Pétrole','Gris','Rose','Vert'],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Bloomé%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Bloomé – Parure de Draps Fleurie','Bloomé – Floral Sheet Set','بلومي – طقم ملاءات زهري','Parure en coton haut de gamme, douceur et motif fleuri élégant.',4500,NULL,ARRAY['/assets/products/bloome_1.jpg','/assets/products/bloome_2.jpg','/assets/products/bloome_3.jpg'],ARRAY['1 Place','2 Places','Bleu Pétrole','Gris','Rose','Vert'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Calm Dreams%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Calm Dreams – Oreiller Confort Hôtelier','Calm Dreams – Hotel Comfort Pillow','كالم دريمز – وسادة فندقية مريحة','Oreiller de confort hôtelier pour un sommeil luxueux.',1000,NULL,ARRAY['/assets/products/calm-dreams-oreiller-de-confort-hotelier_1.jpg','/assets/products/calm-dreams-oreiller-de-confort-hotelier_2.jpg','/assets/products/calm-dreams-oreiller-de-confort-hotelier_3.jpg'],ARRAY[]::text[],cat_oreillers,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Softy Couette%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Softy Couette – Sommeil Royal en Coton','Softy Duvet – Royal Cotton Sleep','سوفتي كوويت – نوم ملكي من القطن','Couette en coton pour des nuits chaudes et confortables.',7900,NULL,ARRAY['/assets/products/couette-softy_1.jpg','/assets/products/couette-softy_2.jpg','/assets/products/couette-softy_3.jpg'],ARRAY['1 Place','2 Places'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Elya%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Elya Oreiller de Prestige Royale','Elya Royal Prestige Pillow','إيليا وسادة الفخامة الملكية','Oreiller de prestige avec soutien doux et confort équilibré.',4500,NULL,ARRAY['/assets/products/elya_1.jpg','/assets/products/elya_2.jpg','/assets/products/elya_3.jpg'],ARRAY[]::text[],cat_oreillers,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE '%ELVA%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Ensemble Sortie de Bain ELVA','ELVA Bath Outfit Set','طقم مناشف الإسبان إلفا','Confort optimal après chaque bain en coton absorbant de qualité.',7900,NULL,ARRAY['/assets/products/ensemble-sortie-de-bain-elva_1.jpg','/assets/products/ensemble-sortie-de-bain-elva_2.jpg','/assets/products/ensemble-sortie-de-bain-elva_3.jpg'],ARRAY['Simple','Couple'],cat_bain,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Horizon%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Horizon – Parure de Draps Rayures Coton Satiné','Horizon – Striped Satin Cotton Sheet Set','هورايزون – طقم ملاءات مخطط قطن ساتان','Parure de draps élégante à rayures en coton satiné.',2500,NULL,ARRAY['/assets/products/horizon_1.jpg','/assets/products/horizon_2.jpg','/assets/products/horizon_3.jpg'],ARRAY['1 Place','2 Places'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Joyful%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Joyful – Beanbag Enfant','Joyful – Kids Beanbag','جويفل – بوف أطفال','Relaxation et élégance pour enfant. Forme ludique et confortable.',10900,NULL,ARRAY['/assets/products/joyful_1.jpg','/assets/products/joyful_2.jpg','/assets/products/joyful_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'LOUNGE DUO%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('LOUNGE DUO – Confort Partagé','LOUNGE DUO – Shared Comfort','لانج ديو – راحة مشتركة','Beanbag double pour un confort partagé. Parfait pour le salon.',19900,NULL,ARRAY['/assets/products/lounge-duo_1.jpg','/assets/products/lounge-duo_2.jpg','/assets/products/lounge-duo_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Luxe Guard%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Luxe Guard – Protecteur de Matelas','Luxe Guard – Mattress Protector','لكس جارد – حافظ الماتلا','Protecteur de matelas en coton anti-humidité, doux et silencieux.',5900,NULL,ARRAY['/assets/products/luxe-guard-protecteur-de-matelas-en-coton_1.jpg','/assets/products/luxe-guard-protecteur-de-matelas-en-coton_2.jpg','/assets/products/luxe-guard-protecteur-de-matelas-en-coton_3.jpg'],ARRAY['90x190','100x190','120x190','140x190','160x200'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'MAJESTIC%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('MAJESTIC – Relaxation et Confort','MAJESTIC – Relaxation and Comfort','ماجستيك – استرخاء وأناقة','Le beanbag Majestic allie luxe et confort pour une expérience d''exception.',16900,NULL,ARRAY['/assets/products/majestic_1.jpg','/assets/products/majestic_2.jpg','/assets/products/majestic_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Matelas ELYSIUM%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Matelas ELYSIUM – Mémoire de Forme D30','ELYSIUM Mattress – D30 Memory Foam','ماتلا إليزيوم – رغوة ميموري فوم','L''harmonie entre confort, soulagement et stabilité. Mousse D30.',15900,NULL,ARRAY['/assets/products/matelas-elysium-memoire-de-forme-d30_1.jpg','/assets/products/matelas-elysium-memoire-de-forme-d30_2.jpg','/assets/products/matelas-elysium-memoire-de-forme-d30_3.jpg'],ARRAY['90x190','100x190','120x190','140x190','160x200'],cat_matelas,15,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Matelas NIRVANA%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Matelas NIRVANA – Mousse D30','NIRVANA Mattress – D30 Foam','مراتب نيرفانا – رغوة كثافة 30','L''alliance parfaite entre soutien orthopédique ferme et accueil moelleux. Garanti 10 ans.',4500,NULL,ARRAY['/assets/products/matelas-nirvana-orthopedique-d30_1.jpg','/assets/products/matelas-nirvana-orthopedique-d30_2.jpg','/assets/products/matelas-nirvana-orthopedique-d30_3.jpg'],ARRAY['90x190','100x190','120x190','140x190','160x200','180x200'],cat_matelas,15,true,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'MONDO%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('MONDO – Expérience de Relaxation','MONDO – Relaxation Experience','موندو – تجربة استرخاء','Beanbag MONDO pour une expérience de relaxation unique.',14900,NULL,ARRAY['/assets/products/mondo_1.jpg','/assets/products/mondo_2.jpg','/assets/products/mondo_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'NEO%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('NEO – Le Confort des Champions','NEO – Champion''s Comfort','نيو – راحة الأبطال','Beanbag NEO design moderne et confort exceptionnel.',15900,NULL,ARRAY['/assets/products/neo_1.jpg','/assets/products/neo_2.jpg','/assets/products/neo_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Pack Calma%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Pack Calma – Solution Literie 5 en 1','Pack Calma – Complete Bedding Set 5 in 1','باك كالما – حزمة ملاءات كاملة 5 في 1','La solution literie complète : draps, housse de couette, taies et plus.',2500,NULL,ARRAY['/assets/products/pack-calma_1.jpg','/assets/products/pack-calma_2.jpg','/assets/products/pack-calma_3.jpg'],ARRAY['1 Place','2 Places'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Pack Elora%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Pack Elora – Couette Literie Complète','Pack Elora – Complete Duvet Set','باك إيلورا – حزمة كوويت كاملة','Ensemble couette literie complet en coton pour un confort total.',15900,NULL,ARRAY['/assets/products/pack-couette-elora_1.jpg','/assets/products/pack-couette-elora_2.jpg','/assets/products/pack-couette-elora_3.jpg'],ARRAY['1 Place','2 Places'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Pack Na%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Pack Naïla – Housse de Couette Coton Premium','Pack Naïla – Premium Cotton Duvet Cover','باك نايلا – غطاء كوويت قطن فاخر','Ensemble housse de couette en coton premium.',15900,NULL,ARRAY['/assets/products/pack-housse-de-couette-naila_1.jpg','/assets/products/pack-housse-de-couette-naila_2.jpg','/assets/products/pack-housse-de-couette-naila_3.jpg'],ARRAY['1 Place','2 Places'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Pack Dova%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Pack Dova – Protection et Confort','Pack Dova – Protection and Comfort','باك دوفا – حماية وراحة','Ensemble protection et confort du matelas.',15900,NULL,ARRAY['/assets/products/pack-linea-protection-et-confort_1.jpg','/assets/products/pack-linea-protection-et-confort_2.jpg','/assets/products/pack-linea-protection-et-confort_3.jpg'],ARRAY['90x190','100x190','120x190','140x190'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Dune%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Dune – Parure de Draps Prestige Percale','Dune – Prestige Percale Sheet Set','دون – طقم ملاءات برستيج بيركال','Parure de draps prestige en percale de coton.',2500,NULL,ARRAY['/assets/products/parure-de-draps-dune_1.jpg','/assets/products/parure-de-draps-dune_2.jpg','/assets/products/parure-de-draps-dune_3.jpg'],ARRAY['1 Place','2 Places'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Sérénité%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Sérénité Parure de Draps – Luxe Hôtelier','Serenity Sheet Set – Hotel Luxury','سيرينيتي – طقم ملاءات أناقة فندقية','Parure de draps luxe hôtelier en coton.',4500,NULL,ARRAY['/assets/products/parure-de-draps-serenite_1.jpg','/assets/products/parure-de-draps-serenite_2.jpg','/assets/products/parure-de-draps-serenite_3.jpg'],ARRAY['1 Place','2 Places'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Pluma%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Pluma – Oreiller Hôtelier Plumes Naturelles','Pluma – Natural Feather Hotel Pillow','بلوما – وسادة فندقية ريش طبيعي','Oreiller hôtelier 5 étoiles en plumes naturelles.',7900,NULL,ARRAY['/assets/products/pluma_1.jpg','/assets/products/pluma_2.jpg','/assets/products/pluma_3.jpg'],ARRAY[]::text[],cat_oreillers,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'POIRE COOL%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('POIRE COOL – Ergonomie Parfaite','POIRE COOL – Perfect Ergonomics','بوا كول – مرونة مثالية','Beanbag POIRE COOL pour une ergonomie parfaite.',9900,NULL,ARRAY['/assets/products/poire-cool_1.jpg','/assets/products/poire-cool_2.jpg','/assets/products/poire-cool_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Poire Grande En Tissu%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Poire Grande Imperméable','Poire Grande Waterproof','بوا归来 كبيرة مقاومة للماء','Beanbag poire grande en tissu imperméable. Idéal pour les terrasses.',13500,NULL,ARRAY['/assets/products/poire-grande-en-tissu-impermeable_1.jpg','/assets/products/poire-grande-en-tissu-impermeable_2.jpg','/assets/products/poire-grande-en-tissu-impermeable_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'POIRE GRANDE – Relaxation%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('POIRE GRANDE – Relaxation Orthopédique','POIRE GRANDE – Orthopedic Relaxation','بوا归来 الكبرى – استرخاء عضوي','La solution idéale pour un confort orthopédique inégalé.',12900,14900,ARRAY['/assets/products/poire-grande_1.jpg','/assets/products/poire-grande_2.jpg','/assets/products/poire-grande_3.jpg'],ARRAY['Beige','Bleu Pétrole','Gris','Jaune','Marron','Noir'],cat_poufs,20,true,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Soft Guard%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Soft Guard – Protège Matelas','Soft Guard – Mattress Protector','سوفت جارد – حافظ الماتلا','Protège matelas protection ultime.',5500,NULL,ARRAY['/assets/products/protege-matelas-soft-guard_1.jpg','/assets/products/protege-matelas-soft-guard_2.jpg','/assets/products/protege-matelas-soft-guard_3.jpg'],ARRAY['90x190','100x190','120x190','140x190'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'SÉLINE%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('SÉLINE – Oreiller Douceur Quotidienne','SELINE – Daily Softness Pillow','سيلين – وسادة النعومة اليومية','Oreiller ergonomique pour un soutien optimal.',2500,NULL,ARRAY['/assets/products/seline_1.jpg','/assets/products/seline_2.jpg','/assets/products/seline_3.jpg'],ARRAY[]::text[],cat_oreillers,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'SOFA G%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('SOFA GÉANTE – Votre Havre de Paix','SOFA GÉANTE – Your Peace Haven','صوفا جِنت – ملاذ السلام','Sofa géante pour un confort maximal.',21600,NULL,ARRAY['/assets/products/sofa-geante_1.jpg','/assets/products/sofa-geante_2.jpg','/assets/products/sofa-geante_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Soft Nuage Classique%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Soft Nuage Classique – Oreiller Mémoire de Forme','Soft Nuage Classic – Memory Foam Pillow','سوفت ناج كلاسيك – وسادة ميموري فوم','Oreiller orthopédique à mémoire de forme, forme classique.',5500,NULL,ARRAY['/assets/products/soft-nuage-classique-oreiller-orthopedique-a-memoire-de-forme_1.jpg','/assets/products/soft-nuage-classique-oreiller-orthopedique-a-memoire-de-forme_2.jpg','/assets/products/soft-nuage-classique-oreiller-orthopedique-a-memoire-de-forme_3.jpg'],ARRAY[]::text[],cat_oreillers,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Soft Nuage Ondulé%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Soft Nuage Ondulé – Oreiller Mémoire de Forme','Soft Nuage Wavy – Memory Foam Pillow','سوفت ناج مموج – وسادة ميموري فوم','Oreiller orthopédique à mémoire de forme, forme ondulée.',5500,NULL,ARRAY['/assets/products/soft-nuage-ondule-oreiller-orthopedique-a-memoire-de-forme_1.jpg','/assets/products/soft-nuage-ondule-oreiller-orthopedique-a-memoire-de-forme_2.jpg','/assets/products/soft-nuage-ondule-oreiller-orthopedique-a-memoire-de-forme_3.jpg'],ARRAY[]::text[],cat_oreillers,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'SUPER RELAX%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('SUPER RELAX – Détente Absolue','SUPER RELAX – Absolute Relaxation','سوبر ريلاكس – استرخاء مطلق','Le beanbag Super Relax pour une détente maximale.',16500,NULL,ARRAY['/assets/products/super-relax_1.jpg','/assets/products/super-relax_2.jpg','/assets/products/super-relax_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Surmatelas SUKOON D30%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Surmatelas SUKOON D30','SUKOON D30 Mattress Topper','سوب ماتلا سوكون دي 30','Soutien stable grâce à la mousse haute densité D30.',2500,NULL,ARRAY['/assets/products/surmatelas-sukoon-d30_1.jpg','/assets/products/surmatelas-sukoon-d30_2.jpg','/assets/products/surmatelas-sukoon-d30_3.jpg'],ARRAY['90x190','100x190','120x190','140x190','160x200'],cat_surmatelas,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Surmatelas SUKOON VISCO%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Surmatelas SUKOON VISCO','SUKOON VISCO Mattress Topper','سوب ماتلا سوكون فيسكو','Mousse à mémoire de forme viscoélastique pour un soutien sur mesure.',9900,NULL,ARRAY['/assets/products/surmatelas-sukoon-visco_1.jpg','/assets/products/surmatelas-sukoon-visco_2.jpg','/assets/products/surmatelas-sukoon-visco_3.jpg'],ARRAY['90x190','100x190','120x190','140x190'],cat_surmatelas,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'Symphonie%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('Symphonie – Parure de Lit Enfant','Symphonie – Kids Bedding Set','سيمفونية – طقم ملاءات أطفال','Parure de lit enfant douceur en coton premium.',6700,NULL,ARRAY['/assets/products/symphonie_1.jpg','/assets/products/symphonie_2.jpg','/assets/products/symphonie_3.jpg'],ARRAY['1 Place'],cat_literie,20,false,true); END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE name_fr LIKE 'VIBE%') THEN INSERT INTO products (name_fr,name_en,name_ar,description_fr,price,compare_at_price,photos,sizes,category_id,stock,featured,active) VALUES ('VIBE – Détente Tout-Terrain','VIBE – All-Terrain Relaxation','فايب – استرخاء كل الأراضي','Beanbag VIBE détente tout-terrain, intérieur et extérieur.',9900,NULL,ARRAY['/assets/products/vibe_1.jpg','/assets/products/vibe_2.jpg','/assets/products/vibe_3.jpg'],ARRAY[]::text[],cat_poufs,20,false,true); END IF;

END $$;

SELECT count(*) as total FROM products WHERE active = true;
